<?php
require_once __DIR__ . '/../core/Controller.php';
require_once __DIR__ . '/../core/Auth.php';
require_once __DIR__ . '/../models/User.php';
require_once __DIR__ . '/../models/Content.php';
class AdminController extends Controller {
  public function __construct(){ Auth::requireRole(['แอดมิน','รัฐบาล']); }
  public function dashboard(): void { $pageTitle='ภาพรวม Green Digital'; $this->view('admin/dashboard.php', compact('pageTitle')); }
  public function users(): void { $pageTitle='จัดการสมาชิก'; $this->view('user/table.php', compact('pageTitle')); }
  public function userForm(): void { require __DIR__ . '/../views/user/form.php'; }
  public function userSave(): void { Auth::verifyCsrf(); $id=(int)$this->input('user_id',0); $d=['full_name'=>trim((string)$this->input('full_name','')),'email'=>strtolower(trim((string)$this->input('email',''))),'role'=>(string)$this->input('role','ประชาชน')]; $m=new User(); if ($id>0) { if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL)) $this->json(['success'=>false,'message'=>'อีเมลไม่ถูกต้อง'],422); $ok=$m->setRole($id,$d['role']) && $m->updateBasic($id,$d); $this->json(['success'=>$ok,'message'=>$ok?'อัปเดตสมาชิกสำเร็จ':'อัปเดตไม่สำเร็จ']); } else { if(!filter_var($d['email'],FILTER_VALIDATE_EMAIL)) $this->json(['success'=>false,'message'=>'อีเมลไม่ถูกต้อง'],422); if($m->existsEmail($d['email'])) $this->json(['success'=>false,'message'=>'อีเมลนี้ถูกใช้แล้ว'],409); $pwd=bin2hex(random_bytes(4)); $newId=$m->create(['email'=>$d['email'],'password'=>password_hash($pwd,PASSWORD_DEFAULT),'full_name'=>$d['full_name'],'role'=>$d['role']]); $this->json(['success'=>true,'message'=>"เพิ่มสมาชิกสำเร็จ (รหัสเริ่มต้น: {$pwd})",'id'=>$newId]); } }
  public function userDelete(): void { Auth::verifyCsrf(); $id=(int)$this->input('id',0); $st=Database::connection()->prepare('DELETE FROM tb_users WHERE user_id=?'); $ok=$st->execute([$id]); $this->json(['success'=>$ok,'message'=>$ok?'ลบสมาชิกสำเร็จ':'ลบไม่สำเร็จ']); }
  public function contents(): void { $pageTitle='จัดการเนื้อหา'; $this->view('content/table.php', compact('pageTitle')); }
  private function uploadImage(string $fieldName, ?string $currentPath=null): ?string { if(!isset($_FILES[$fieldName]) || $_FILES[$fieldName]['error']===UPLOAD_ERR_NO_FILE) return $currentPath; $f=$_FILES[$fieldName]; if($f['error']!==UPLOAD_ERR_OK) throw new RuntimeException('อัปโหลดไฟล์ไม่สำเร็จ'); $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']); $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/gif'=>'gif','image/webp'=>'webp']; if(!isset($allowed[$mime])) throw new RuntimeException('ชนิดไฟล์ไม่รองรับ'); if($f['size']>3*1024*1024) throw new RuntimeException('ไฟล์ใหญ่เกินกำหนด 3MB'); $dir=dirname(__DIR__,2).'/public/uploads'; if(!is_dir($dir)) @mkdir($dir,0775,true); $name=bin2hex(random_bytes(8)).'.'.$allowed[$mime]; $target=$dir.'/'.$name; if(!move_uploaded_file($f['tmp_name'],$target)) throw new RuntimeException('ย้ายไฟล์ไม่สำเร็จ'); if($currentPath){ $old=dirname(__DIR__,2).'/public'.$currentPath; if(is_file($old)) @unlink($old); } return '/uploads/'.$name; }
  public function contentForm(): void { require __DIR__ . '/../views/content/form.php'; }
  public function contentSave(): void { Auth::verifyCsrf(); $id=(int)$this->input('content_id',0); $m=new Content(); $cur=$id?$m->find($id):null; $d=['title'=>trim((string)$this->input('title','')),'body'=>(string)$this->input('body',''),'image_path'=>$this->uploadImage('image', $cur['image_path']??null),'publish_at'=>$this->input('publish_at','')?:null,'expire_at'=>$this->input('expire_at','')?:null,'is_active'=>(int)$this->input('is_active',1)]; try { if ($id>0) { $ok=$m->save($d,$id); $this->json(['success'=>$ok,'message'=>'อัปเดตเนื้อหาสำเร็จ']); } else { $newId=$m->save($d,null); $this->json(['success'=>true,'message'=>'เพิ่มเนื้อหาสำเร็จ','id'=>$newId]); } } catch(Throwable $e) { $this->json(['success'=>false,'message'=>'เกิดข้อผิดพลาด','error'=>$e->getMessage()],500); } }
  public function contentDelete(): void { Auth::verifyCsrf(); $id=(int)$this->input('id',0); $m=new Content(); $c=$m->find($id); $ok=$m->delete($id); if($ok && $c && $c['image_path']){ $p=dirname(__DIR__,2).'/public'.$c['image_path']; if(is_file($p)) @unlink($p); } $this->json(['success'=>$ok,'message'=>$ok?'ลบเนื้อหาสำเร็จ':'ลบไม่สำเร็จ']); }
}
