
<?php
require_once __DIR__ . '/../core/Controller.php';
require_once __DIR__ . '/../core/Auth.php';
require_once __DIR__ . '/../models/WasteType.php';
require_once __DIR__ . '/../models/WasteRecord.php';
require_once __DIR__ . '/../models/Organization.php';
class WasteController extends Controller {
  public function __construct(){ Auth::requireLogin(); }
  public function types(): void { Auth::requireRole(['แอดมิน','รัฐบาล']); $pageTitle='ประเภทขยะ'; $contentViewPath=__DIR__.'/../views/waste/types.table.php'; $this->view('components/content.php', compact('pageTitle','contentViewPath')); }
  public function typeForm(): void { Auth::requireRole(['แอดมิน','รัฐบาล']); require __DIR__.'/../views/waste/types.form.php'; }
  public function typeSave(): void { Auth::requireRole(['แอดมิน','รัฐบาล']); Auth::verifyCsrf(); $id=(int)$this->input('type_id',0); $d=['type_name'=>trim((string)$this->input('type_name','')),'type_unit'=>trim((string)$this->input('type_unit','')),'type_cash'=>(string)$this->input('type_cash','0')]; $m=new WasteType(); if ($id>0){ $ok=$m->save($d,$id); $this->json(['success'=>$ok,'message'=>'อัปเดตประเภทขยะสำเร็จ']); } else { $newId=$m->save($d,null); $this->json(['success'=>true,'message'=>'เพิ่มประเภทขยะสำเร็จ','id'=>$newId]); } }
  public function typeDelete(): void { Auth::requireRole(['แอดมิน','รัฐบาล']); Auth::verifyCsrf(); $id=(int)$this->input('id',0); $ok=(new WasteType())->delete($id); $this->json(['success'=>$ok,'message'=>$ok?'ลบประเภทสำเร็จ':'ลบไม่สำเร็จ']); }
  private function uploadImage(string $fieldName, ?string $currentPath=null): ?string { if(!isset($_FILES[$fieldName]) || $_FILES[$fieldName]['error']===UPLOAD_ERR_NO_FILE) return $currentPath; $f=$_FILES[$fieldName]; if($f['error']!==UPLOAD_ERR_OK) throw new RuntimeException('อัปโหลดไฟล์ไม่สำเร็จ'); $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']); $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/gif'=>'gif','image/webp'=>'webp']; if(!isset($allowed[$mime])) throw new RuntimeException('ชนิดไฟล์ไม่รองรับ'); if($f['size']>3*1024*1024) throw new RuntimeException('ไฟล์ใหญ่เกินกำหนด 3MB'); $dir=dirname(__DIR__,2).'/public/uploads'; if(!is_dir($dir)) @mkdir($dir,0775,true); $name=bin2hex(random_bytes(8)).'.'.$allowed[$mime]; $target=$dir.'/'.$name; if(!move_uploaded_file($f['tmp_name'],$target)) throw new RuntimeException('ย้ายไฟล์ไม่สำเร็จ'); if($currentPath){ $old=dirname(__DIR__,2).'/public'.$currentPath; if(is_file($old)) @unlink($old); } return '/uploads/'.$name; }
  public function records(): void { $pageTitle='บันทึกขยะ'; $contentViewPath=__DIR__.'/../views/waste/rec.table.php'; $orgs=(new Organization())->list(); $this->view('components/content.php', compact('pageTitle','contentViewPath','orgs')); }
  public function recordForm(): void { require __DIR__.'/../views/waste/rec.form.php'; }
  public function recordSave(): void { Auth::verifyCsrf(); $id=(int)$this->input('rec_id',0); $m=new WasteRecord(); $cur=$id?$m->find($id):null; $d=['user_id'=>Auth::id(),'org_id'=>(int)$this->input('org_id',0),'type_id'=>(int)$this->input('type_id',0),'weight'=>(string)$this->input('weight','0'),'note'=>trim((string)$this->input('note','')),'status'=>(string)$this->input('status','ใช้งานอยู่'),'was_image'=>$this->uploadImage('was_image', $cur['was_image']??null)]; try { if($id>0){ $ok=$m->save($d,$id); $this->json(['success'=>$ok,'message'=>'อัปเดตบันทึกสำเร็จ']); } else { $newId=$m->save($d,null); $this->json(['success'=>true,'message'=>'บันทึกขยะสำเร็จ','id'=>$newId]); } } catch(Throwable $e){ $this->json(['success'=>false,'message'=>'เกิดข้อผิดพลาด','error'=>$e->getMessage()],500); } }
  public function recordDelete(): void { Auth::verifyCsrf(); $id=(int)$this->input('id',0); $m=new WasteRecord(); $r=$m->find($id); $ok=$m->delete($id); if($ok && $r && $r['was_image']){ $p=dirname(__DIR__,2).'/public'.$r['was_image']; if(is_file($p)) @unlink($p); } $this->json(['success'=>$ok,'message'=>$ok?'ลบบันทึกสำเร็จ':'ลบไม่สำเร็จ']); }
}
